spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entites
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microserviceloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #org.gjt.mm.mysql.Driver com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root123
    dbcp2:
      min-idle: 5   #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      validation-query: SELECT 'x'
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entites
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: microserviceloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #org.gjt.mm.mysql.Driver com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root123
    dbcp2:
      min-idle: 5   #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      validation-query: SELECT 'x'
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$